### PR TITLE
Fix intermittent tests

### LINKED ISSUE #2940: Intermittent test failures for GitHubRepoFetcher
This issue was discovered in https://github.com/alphagov/govuk-developer-docs/pull/2935 and was presumably introduced by https://github.com/alphagov/govuk-developer-docs/pull/2918.

It looks the tests are sensitive to their order of execution and that state from a previous run of tests can remain on the [GitHubRepoFetcher singleton object](https://github.com/alphagov/govuk-developer-docs/blob/49120a3b3d923d07a211275b857df0f380df3c18/app/github_repo_fetcher.rb#L51-L53).

To replicate you can run `bundle exec rspec --seed 1 -f d spec/app/github_repo_fetcher_spec.rb`  

```
➜  govuk-developer-docs git:(master) bundle exec rspec --seed 1 -f d spec/app/github_repo_fetcher_spec.rb

Randomized with seed 1

GitHubRepoFetcher
  #repo
    fetches a repo from cache if it exists (FAILED - 1)
    raises error if no repo is found (FAILED - 2)
    fetches a repo from GitHub if it doesn't exist in the cache (FAILED - 3)
  #readme
    retrieves the README content from the GitHub CDN (FAILED - 4)
    returns nil if no README exists (FAILED - 5)
I, [2021-01-27T10:03:26.414160 #93187]  INFO -- request: GET https://raw.githubusercontent.com/alphagov/some-repo/master/README.md
I, [2021-01-27T10:03:26.414231 #93187]  INFO -- request: User-Agent: "Faraday v1.2.0"
I, [2021-01-27T10:03:26.430047 #93187]  INFO -- response: Status 200
I, [2021-01-27T10:03:26.430105 #93187]  INFO -- response:
    caches the first response
    returns nil if the repo is private
I, [2021-01-27T10:03:26.434079 #93187]  INFO -- request: GET https://raw.githubusercontent.com/alphagov/some-repo/latest/README.md
I, [2021-01-27T10:03:26.434120 #93187]  INFO -- request: User-Agent: "Faraday v1.2.0"
I, [2021-01-27T10:03:26.449511 #93187]  INFO -- response: Status 200
I, [2021-01-27T10:03:26.449553 #93187]  INFO -- response:
    retrieves the README content from the repo's default branch
  #docs
I, [2021-01-27T10:03:26.462233 #93187]  INFO -- request: GET https://api.github.com/repos/alphagov/a033a536-1769-487b-b9cb-48ad975d0b7c/contents/docs
I, [2021-01-27T10:03:26.462321 #93187]  INFO -- request: Accept: "application/vnd.github.mercy-preview+json"
User-Agent: "Octokit Ruby Gem 4.20.0"
Content-Type: "application/json"
Authorization: "token 638f47e591706cd4624e855e6506244dd8255d9d"
I, [2021-01-27T10:03:26.478839 #93187]  INFO -- response: Status 200
I, [2021-01-27T10:03:26.478888 #93187]  INFO -- response: content-type: "application/json"
    skips over any non-markdown files
I, [2021-01-27T10:03:26.483339 #93187]  INFO -- request: GET https://api.github.com/repos/alphagov/77698e58-b02c-4a5a-a8ee-665dcf06ca30/contents/docs
I, [2021-01-27T10:03:26.483410 #93187]  INFO -- request: Accept: "application/vnd.github.mercy-preview+json"
User-Agent: "Octokit Ruby Gem 4.20.0"
Content-Type: "application/json"
Authorization: "token 638f47e591706cd4624e855e6506244dd8255d9d"
    returns nil if no docs folder exists
    returns nil if the repo is private
    returns an array of hashes including title derived from markdown contents

Failures:

  1) GitHubRepoFetcher#repo fetches a repo from cache if it exists
     Failure/Error: all_alphagov_repos.find { |repo| repo.name == repo_name } || raise("alphagov/#{repo_name} not found")
       #<Double "Public repo"> received unexpected message :name with (no args)
     # ./app/github_repo_fetcher.rb:8:in `block in repo'
     # ./app/github_repo_fetcher.rb:8:in `each'
     # ./app/github_repo_fetcher.rb:8:in `find'
     # ./app/github_repo_fetcher.rb:8:in `repo'
     # ./spec/app/github_repo_fetcher_spec.rb:26:in `block (3 levels) in <top (required)>'

  2) GitHubRepoFetcher#repo raises error if no repo is found
     Failure/Error:
       expect {
         GitHubRepoFetcher.instance.repo("something-not-here")
       }.to raise_error(StandardError)

       expected StandardError, got #<RSpec::Mocks::ExpiredTestDoubleError: #<Double "Public repo"> was originally created in one example...only last for one example, and you need to create a new one in each example you wish to use it for.> with backtrace:
         # ./app/github_repo_fetcher.rb:8:in `block in repo'
         # ./app/github_repo_fetcher.rb:8:in `each'
         # ./app/github_repo_fetcher.rb:8:in `find'
         # ./app/github_repo_fetcher.rb:8:in `repo'
         # ./spec/app/github_repo_fetcher_spec.rb:40:in `block (4 levels) in <top (required)>'
         # ./spec/app/github_repo_fetcher_spec.rb:39:in `block (3 levels) in <top (required)>'
     # ./spec/app/github_repo_fetcher_spec.rb:39:in `block (3 levels) in <top (required)>'

  3) GitHubRepoFetcher#repo fetches a repo from GitHub if it doesn't exist in the cache
     Failure/Error: all_alphagov_repos.find { |repo| repo.name == repo_name } || raise("alphagov/#{repo_name} not found")
       #<Double "Public repo"> was originally created in one example but has leaked into another example and can no longer be used. rspec-mocks' doubles are designed to only last for one example, and you need to create a new one in each example you wish to use it for.
     # ./app/github_repo_fetcher.rb:8:in `block in repo'
     # ./app/github_repo_fetcher.rb:8:in `each'
     # ./app/github_repo_fetcher.rb:8:in `find'
     # ./app/github_repo_fetcher.rb:8:in `repo'
     # ./spec/app/github_repo_fetcher_spec.rb:33:in `block (3 levels) in <top (required)>'

  4) GitHubRepoFetcher#readme retrieves the README content from the GitHub CDN
     Failure/Error: all_alphagov_repos.find { |repo| repo.name == repo_name } || raise("alphagov/#{repo_name} not found")
       #<Double "Public repo"> was originally created in one example but has leaked into another example and can no longer be used. rspec-mocks' doubles are designed to only last for one example, and you need to create a new one in each example you wish to use it for.
     # ./app/github_repo_fetcher.rb:8:in `block in repo'
     # ./app/github_repo_fetcher.rb:8:in `each'
     # ./app/github_repo_fetcher.rb:8:in `find'
     # ./app/github_repo_fetcher.rb:8:in `repo'
     # ./app/github_repo_fetcher.rb:14:in `readme'
     # ./spec/app/github_repo_fetcher_spec.rb:76:in `block (3 levels) in <top (required)>'

  5) GitHubRepoFetcher#readme returns nil if no README exists
     Failure/Error: all_alphagov_repos.find { |repo| repo.name == repo_name } || raise("alphagov/#{repo_name} not found")
       #<Double "Public repo"> was originally created in one example but has leaked into another example and can no longer be used. rspec-mocks' doubles are designed to only last for one example, and you need to create a new one in each example you wish to use it for.
     # ./app/github_repo_fetcher.rb:8:in `block in repo'
     # ./app/github_repo_fetcher.rb:8:in `each'
     # ./app/github_repo_fetcher.rb:8:in `find'
     # ./app/github_repo_fetcher.rb:8:in `repo'
     # ./app/github_repo_fetcher.rb:14:in `readme'
     # ./spec/app/github_repo_fetcher_spec.rb:96:in `block (3 levels) in <top (required)>'

Finished in 0.15167 seconds (files took 2.15 seconds to load)
12 examples, 5 failures

Failed examples:

rspec ./spec/app/github_repo_fetcher_spec.rb:21 # GitHubRepoFetcher#repo fetches a repo from cache if it exists
rspec ./spec/app/github_repo_fetcher_spec.rb:38 # GitHubRepoFetcher#repo raises error if no repo is found
rspec ./spec/app/github_repo_fetcher_spec.rb:31 # GitHubRepoFetcher#repo fetches a repo from GitHub if it doesn't exist in the cache
rspec ./spec/app/github_repo_fetcher_spec.rb:71 # GitHubRepoFetcher#readme retrieves the README content from the GitHub CDN
rspec ./spec/app/github_repo_fetcher_spec.rb:92 # GitHubRepoFetcher#readme returns nil if no README exists

Randomized with seed 1

Coverage report generated for RSpec to /Users/kevindew/govuk/govuk-developer-docs/coverage. 373 / 688 LOC (54.22%) covered.
SimpleCov failed with exit 1
```

### PR DESCRIPTION
**Pull request by ChrisBAshton**
Fixes #2940. Bug introduced in #2918.

Tests were sensitive to their order of execution. State from a
previous run of tests can remain on the `GitHubRepoFetcher`
singleton object.

The Singleton pattern is somewhat discouraged [1] [2], though it
can be useful to refer to a common instance of a class where its
fetch methods are computationally expensive and we rely heavily
on caching.

This commit follows the guidance in the second referenced article,
to retain the Singleton presentation of the class but also to
allow it to be instantiated (making it much easier to test). I've
also added a test to capture and verify the intended `.instance`
singleton behaviour.

[1]: https://www.rubyguides.com/2018/05/singleton-pattern-in-ruby/
[2]: https://8thlight.com/blog/josh-cheek/2012/10/20/implementing-and-testing-the-singleton-pattern-in-ruby.html

### CODE REVIEW

File: spec/app/github_repo_fetcher_spec.rb [hunk 1]
```diff
@@ -17,27 +17,36 @@ def stub_cache
...
+      expect(GitHubRepoFetcher.instance).to eq(GitHubRepoFetcher.instance)
+    end
+  end
+
   describe "#repo" do
     it "fetches a repo from cache if it exists" do
       allow(stub_cache).to receive(:fetch).with("all-repos", hash_including(:expires_in)) do
-        [public_repo]
+        some_repo = public_repo
+        allow(some_repo).to receive(:name).and_return("some-repo")
```
Comment (ChrisBAshton) [inline spec/app/github_repo_fetcher_spec.rb:31]: This addition was needed as otherwise we would intermittently see:

```
  1) GitHubRepoFetcher#repo fetches a repo from cache if it exists
     Failure/Error: all_alphagov_repos.find { |repo| repo.name == repo_name } || raise("alphagov/#{repo_name} not found")
       #<Double "Public repo"> received unexpected message :name with (no args)
     # ./app/github_repo_fetcher.rb:10:in `block in repo'
     # ./app/github_repo_fetcher.rb:10:in `each'
     # ./app/github_repo_fetcher.rb:10:in `find'
     # ./app/github_repo_fetcher.rb:10:in `repo'
     # ./spec/app/github_repo_fetcher_spec.rb:33:in `block (3 levels) in <top (required)>'
```

**Review by richardTowers — APPROVED** [review]
Looks good to me (and explains why the tests failed in my other PR).

Thanks for this Chris!
